version: "3"

name: verzel-motors
services:

  fastapi:
    container_name: fastapi
    build:
      context:  ../backend
      target: prod
    restart: always
    env_file:
      - ../backend/.env
      - .env
    ports:
      - ${DOCKER_LOCAL_SERVER_PORT:-8000}:8000
    volumes:
      - ../backend/:/usr/app/
    networks:
      - verzel-motors

  react:
    container_name: react
    build:
      context:  ../frontend
      target: prod
    restart: always
    env_file:
      - ../frontend/.env
      - .env
    tty: true
    ports:
      - 5173:5173
      - 3000:3000
    volumes:
      - ../frontend/:/usr/app/
      - /usr/app/node_modules/
      - /usr/app/dist/
    links:
      - fastapi
    depends_on:
      - fastapi
    networks:
      - verzel-motors

networks:
  verzel-motors:

